dev
ianikeyenka/library-api pull request #1
Opened 2024-02-01 13:17 UTC by ianikeyenka

2024-02-06 06:43 UTC, AbandonedScope requested changes

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +@RequestMapping("/api")
Добавь версионирование api, я имею ввиду, что-то вроде "api/v1" чтобы было + почитай, почему так нужно делать

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +    public ResponseEntity<List<BookDTO>> getBooks() {
Лучше оборачивай List<BookDTO> в dto - так проще будет потом добавлять доп. поля, если понадобится
+ называй не BookDTO, a BookDto, а лучше вообще BookResponse

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +        List<BookDTO> bookDTOS = bookService.getBooks();
bookDTOS - плохой нейминг, я и так понимаю, что там лежит, да и название должно быть в camelcase - bookDtos (или bookDTOs)

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +    @GetMapping("/books")
books можно вынести на уровень контроллера

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +        bookService.addBook(bookDTO);
Возвращай в ответ пользователю то, что было создано в результате работы метода addBook - там должна же по идее генерироваться id-шка

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Тут можно возвращать удалённую сущность

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/dto/BookDTO.java
> +    @Pattern(regexp = "(^\\d{3}-\\d{2}-\\d{5}-\\d{2}-\\d$)",
Регулярные выражения выноси в константы в отдельный класс

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/exception/BookExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,
Исключение `MethodArgumentNotValidException ` можно обработать таким же способом, как ты делал с `ResourceNotFoundException`, нет нужды наследоваться от `ResponseEntityExceptionHandler ` и переопределять его метод

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/model/BookModel.java
> +public class BookModel {
Можно было без Model, просто Book

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/model/BookModel.java
> +    @Column
Аннотация `@Column` не обязательна

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/BookService.java
> +    void addBook(BookDTO bookDTO);
Я бы назвал иначе - addBook - не очень понятно, куда мы её добавляем, лучше уж saveBook или что-то подобное

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +        existingBook.setAuthor(bookDTO.getAuthor());
Это можно вынести в отдельный метод

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +                        )));
Вот это можно вынести в отдельный метод и назвать как-нибудь по типу getOrThrow

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +        existingBook.setName(bookDTO.getName());
А если названия совпадают?

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
В этом классе(по крайней мере сейчас) транзакции не нужны - они необходимы тогда, когда ты выполняешь несколько операций над данными и тебе нужно откатить изменения внесённые в бд в случае возникновения каких-то ошибок

2024-02-06 06:43 UTC, AbandonedScope commented on book-service/src/main/resources/db/changelog/v-1.0/01-changeset-books-table.xml
> +    <changeSet id="2" author="ianikeyenka">
Лучше здесь поставить id 1, а в db.changelog-master.xml в tag="v.1.0" поставить id 2

2024-02-08 20:13 UTC, AbandonedScope requested changes

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/pom.xml
Выноси номера версий зависимостей в тег properties

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +        List<BookResponse> bookResponses = bookService.getBooks();
Создай дто и возвращай не List<BookResponse>, а BookListResponse

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +        return new ResponseEntity<>(bookResponses, HttpStatus.OK);
У класса ResponseEntity есть большое кол-во статических методов для создания объектов, используй лучше их, а не просто конструктор

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/controller/BookController.java
> +    @PatchMapping("/{id}")
Patch применяется для обновления одного поля, если здесь происходит обновление всей сущности, то используй метод Post

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/exception/BookExceptionHandler.java
> +        ErrorResponseInformation errorResponse = new ErrorResponseInformation(
У Lombok есть аннотация `@Builder` используй её на этом классе и тогда создание объекта будет выглядеть получше и не придётся запоминать порядок полей класса

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    }
А вот теперь можно добавить транзакцию (на самом деле зависит от логики)
Смотри, если мы не хотим, чтобы в базе была запись о книге, сообщение о который не смогло отправиться через кафку (предположим, что  kafkaTemplate.send выбросило какое-то исключение) то нам нужно выполнять это в рамках транзакции, чтобы откатить внесённые изменения и удалить книгу(ну и понятно, что пользователю должно вернуться сообщение об ошибке)

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    }
Смотри, этот метод используется в методе updateBook, поэтому, чтобы сделать код более читаемым, предпочтительно расположить его сразу под методом updateBook

2024-02-08 20:13 UTC, AbandonedScope commented on book-service/src/main/resources/db/changelog/db.changelog-master.xml
> +    <changeSet id="3" author="ianikeyenka">
Тут по идее должен был быть id 4, а в самом changeSet с миграцией id 3

2024-02-08 20:13 UTC, AbandonedScope commented on library-service/pom.xml
Выноси номера версий зависимостей в тег properties

2024-02-08 20:13 UTC, AbandonedScope commented on library-service/src/main/java/com/example/libraryservice/controller/BookTrackerController.java
> +        return new ResponseEntity<>(bookTrackerService.getBookTrackers(), HttpStatus.OK);
ТО же самое, оберни List<BookTrackerResponse> в дто

2024-02-22 09:53 UTC, yahorposkanny21 commented on auth-service/src/main/java/com/example/authservice/config/JwtGenerator.java
> +                .setIssuedAt( new Date())
пробелы лишние

2024-02-22 09:53 UTC, yahorposkanny21 commented on auth-service/src/main/java/com/example/authservice/config/JwtGenerator.java
> +        System.out.println("New token :");
один sout можно оставить через /n перенос сделать

2024-02-22 09:58 UTC, yahorposkanny21 commented on auth-service/src/main/java/com/example/authservice/repository/UserRepository.java
> +    Boolean existsByUsername(String username);
boolean

2024-02-22 10:00 UTC, yahorposkanny21 commented on auth-service/src/main/java/com/example/authservice/service/impl/UserServiceImpl.java
> +    @Autowired
попробуй инжектить бины через @RequiredArgsConstructor, тогда конструктор тут не понадобиться

2024-02-22 10:02 UTC, yahorposkanny21 commented on auth-service/src/main/java/com/example/authservice/controller/AuthController.java
> +        if (userRepository.existsByUsername(registerRequest.getUsername())) {
existsByUsername можно создать в UserService, тогда только одна зависимость тут будет, репозиторий не надо будет автовайрить, да и в целом плохо автовайрить репозиторий в контроллер

2024-02-22 10:05 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/dto/BookRequest.java
> +import static com.example.bookservice.util.Constant.AUTHOR_SIZE;
import static com.example.bookservice.util.Constant.*;

2024-02-22 10:07 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +import static com.example.bookservice.util.Constant.BOOK_NOT_FOUND_BY_ID;
тоже самое

2024-02-22 10:09 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private Book getBookByIsbnOrThrow(String isbn) {
вынеси метод в BookService

2024-02-22 10:13 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +        kafkaTemplate.send("bookTrackerTopic", book.getId());
в идеале для работы с кафкой тоже должен быть отдельный класс, например продюссер или консьюмер и там уже метод send вызывается внутри метода этого класса

2024-02-22 10:14 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private void existingIsbn(String isbn) {
тоже самое

2024-02-22 10:15 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private void updateExistingBook(Book existingBook, BookRequest newBook) {
можно попробовать использовать @Builder

2024-02-22 10:15 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private Book getBookByIdOrThrow(Long id) {
и тут

2024-02-22 10:17 UTC, yahorposkanny21 commented on library-service/src/main/java/com/example/libraryservice/repository/BookTrackerRepository.java
> +    @Query("from BookTracker as t where CURRENT_DATE > t.dateToReturn")
List<BookTracker> findByDateToReturnBefore(LocalDate currentDate);

2024-02-22 11:56 UTC, ianikeyenka commented on book-service/src/main/java/com/example/bookservice/dto/BookRequest.java
> +import static com.example.bookservice.util.Constant.AUTHOR_SIZE;
Разве так стоит делать, если собираемся использовать не все статические поля из этого класса?

2024-02-22 12:23 UTC, ianikeyenka commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private Book getBookByIsbnOrThrow(String isbn) {
Я реализовывал тут вспомогательное метод для того, чтобы убрать повторение в некоторых случаях, ну и повысить читабельность. Зачем делать публичным, если уже есть то, что выполняет это?

2024-02-26 09:04 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/dto/BookRequest.java
> +import static com.example.bookservice.util.Constant.AUTHOR_SIZE;
да, нужно так

2024-02-26 09:05 UTC, yahorposkanny21 commented on book-service/src/main/java/com/example/bookservice/service/impl/BookServiceImpl.java
> +    private Book getBookByIsbnOrThrow(String isbn) {
ок, оставь так

2024-02-28 16:32 UTC, merged